Resolve symlinks for app:///[...] and file:///[...] URLs on Windows
BabylonJS/UrlLib pull request #10
Opened 2023-09-07 00:21 UTC by docEdub

On macOS and Linux, app:/// and file:/// URLs that point to symlinks automatically resolve to the target file, but not on Windows.

This change resolves symlinks programmatically on Windows so the behavior is consistent across all platforms.

Unit tests are in the JsRuntimeHost repo in PR https://github.com/BabylonJS/JsRuntimeHost/pull/49.

2023-09-07 08:07 UTC, CedricGuillemet approved these changes
LGTM but I'll let @bghgary have the final word :)

2023-09-07 20:28 UTC, bghgary requested changes

2023-09-07 20:28 UTC, bghgary commented on Source/UrlRequest_Windows.cpp
> +        }
I just did a test in a standalone app and the WinRT APIs seem to follow symlinks just fine. Why is this necessary?

2023-09-07 20:53 UTC, bghgary commented on Source/UrlRequest_Windows.cpp
> +        }
Just tried in a Win32 BN playground. It looks like the WinRT Storage API is throwing these errors:
```
Exception thrown at 0x00007FF88C554C3C (KernelBase.dll) in Playground.exe: WinRT originate error - 0x80070005 : 'Cannot access the specified file or folder (D:\GitHub\BabylonJS\BabylonNative\Build\Win32\Apps\Playground\Debug\Scripts\experience2.js). Verify that the item is not marked with system or hidden file attributes.'.
Exception thrown at 0x00007FF88C554C3C (KernelBase.dll) in Playground.exe: WinRT originate error - 0x80070005 : 'Access is denied.'.
```
This is strange.

2023-09-07 21:43 UTC, bghgary commented on Source/UrlRequest_Windows.cpp
> +        }
I tested the UWP BN playground and it can load symlinks just fine, so something about using this API outside of an app container is causing an issue.

2023-09-07 23:12 UTC, bghgary commented on Source/UrlRequest_Windows.cpp
> +        }
Ok, I debugged the OS a bit. I think we should stop using WinRT APIs for loading local files for Win32. This code is way more complicated than we want it to be. We can use Win32 APIs directly instead. Just need to make sure to use the async versions (using the overlapped structure).

2023-10-02 15:45 UTC, docEdub commented
Replaced by PR https://github.com/BabylonJS/UrlLib/pull/11/.

2023-10-02 15:45 UTC, closed without merging